version: "3.3"
services:

  portainer:
    image: portainer/portainer:1.22.1
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  sdp:
    image: dbene/simple-dash-particles:latest
    container_name: simple-dash-particles
    ports:
      - 80:80
    volumes:
      - ${SDP_CONF_DIR}:/usr/share/nginx/html/config/
    restart: unless-stopped

volumes:
  portainer_data:
