scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: SCRAPE_INTERVALs
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'HOST_NAME'
    scrape_interval: SCRAPE_INTERVALs
    static_configs:
    - targets: ['HOST_IP:9100']
    